module.exports = {
  FRIENDS_INSERT_OR_UPDATE: 'FRIENDS_INSERT_OR_UPDATE',
  CHAT_NEW_INCOMING_MESSAGE: 'CHAT_NEW_INCOMING_MESSAGE',
  CHAT_NEW_OUTGOING_MESSAGE: 'CHAT_NEW_OUTGOING_MESSAGE',

  MessageTypes: {
    CHAT_OUR_MESSAGE: 'our-message',
    CHAT_THEIR_MESSAGE: 'their-message'
  }
};
